vars: {
  d2-config: {
    layout-engine: elk
    center: true
  }
}
db_model: "URL Shortener DB Schema" {
  url_mapping: {
    shape: sql_table
    id: int {constraint: primary_key}
    short_url: varchar (10) {constraint: unique}
    long_url: varchar {constraint: unique}
    created_at: timestamp
    expires_at: timestamp
    user_id: int {constraint: foreign_key}
    click_count: int
  }

  user: {
    shape: sql_table
    id: int
    username: varchar
    email: varchar
  }
  url_mapping.user_id -> user.id
}
